# Generated by Django 3.1.dev20200220140547 on 2020-03-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_cafedra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Cafedra'),
        ),
    ]
