# Generated by Django 3.1.dev20200220140547 on 2020-03-20 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20200319_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('max_points', models.IntegerField(default=100)),
                ('min_points', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.Course')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
