# Generated by Django 3.1.dev20200220140547 on 2020-05-03 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20200503_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_id', to='quizzes.Quiz'),
        ),
    ]
