# Generated by Django 3.1.dev20200220140547 on 2020-05-04 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_auto_20200503_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('correct', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_id', to='quizzes.Questions')),
            ],
        ),
    ]
