# Generated by Django 3.1.dev20200220140547 on 2020-05-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_auto_20200504_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.TextField(),
        ),
    ]
