# Generated by Django 3.1.dev20200220140547 on 2020-05-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_auto_20200507_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
